<?php
$isNew=isset($_GET['new']);$editorRows=$isNew?array_fill(0,3,[]):$formRows;$editorHead=$isNew?[]:$head;$editorDetails=$isNew?[]:$details;
$editorColumns=form_columns($formType);
$editorItemLabels=match($formType){
  'RIS'=>['Stock No.','Unit','Description','Requisition / Issue Quantity','Stock Available / Remarks'],
  'Stock Card'=>['Reference','Unit','Description','Receipt Quantity','Issue / Balance / Days to Consume'],
  'Supply Ledger Card'=>['Reference','Unit','Description','Quantity','Receipt / Issue / Balance Costs'],
  'RSMI'=>['Stock No.','Unit','Item','Quantity Issued','Unit Cost / Amount'],
  'Waste Materials Report'=>['Item','Unit','Description','Quantity','Official Receipt No. / Date / Amount'],
  'RPCI'=>['Stock Number','Unit of Measure','Article / Description','On Hand Quantity','Unit Value / Balance / Shortage / Overage / Remarks'],
  default=>['Reference','Unit','Description','Quantity','Remarks']
};
?>
<style>.editor-actions{display:flex;gap:9px;margin-bottom:14px}.form-editor{margin-bottom:18px}.editor-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:18px}.editor-grid label{font-size:10px;font-weight:700;color:#526575}.editor-grid input{display:block;width:100%;margin-top:6px}.item-editor{border-top:1px solid #e4e9ef;padding-top:16px}.item-editor-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:10px}#itemTable{min-width:850px}#itemTable input,#itemTable textarea{width:100%;border:1px solid #d7dfe7;border-radius:6px;padding:7px;font:10px Inter}#itemTable textarea{min-height:58px;resize:vertical}#itemTable .remove{border:0;background:none;color:#dc2626;font-size:9px;cursor:pointer}.signatures-input{margin-top:18px}@media(max-width:900px){.editor-grid{grid-template-columns:1fr 1fr}}@media(max-width:650px){.editor-grid{grid-template-columns:1fr}}</style>
<section class="panel form-editor">
  <div class="panelhead"><div><small><?=e($isNew?'NEW FORM':'EDIT FORM')?></small><h3><?=e(form_title($formType))?></h3></div><a href="?page=forms&type=<?=urlencode($formType)?>&ref=<?=urlencode($ref)?>">Cancel</a></div>
  <form method="post" id="editableForm">
    <input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save_form"><input type="hidden" name="form_type" value="<?=e($formType)?>"><input type="hidden" name="old_reference" value="<?=e($isNew?'':$ref)?>">
    <div class="editor-grid"><label><?=e(form_reference_label($formType))?><input name="reference_no" value="<?=e($isNew?'':$ref)?>" required></label><label>Date<input type="date" name="form_date" value="<?=e($editorHead['date']??date('Y-m-d'))?>"></label><label>Fund Cluster<input name="fund_cluster" value="<?=e($editorDetails['Fund Cluster']??'')?>"></label><label><?=e(form_left_meta($formType))?><input name="office" value="<?=e($editorHead['office']??($editorDetails['Division']??''))?>"></label><label><?=e(form_party_label($formType))?><input name="party" value="<?=e($editorHead['party']??'')?>"></label><label><?=e(form_notes_label($formType))?><input name="purpose" value="<?=e($editorDetails['Purpose']??'')?>"></label></div>
    <div class="item-editor"><div class="item-editor-head"><h3>Official Form Entries</h3><button type="button" class="btn" onclick="addItemRow()">+ Add item</button></div><div class="scroll"><table id="itemTable"><thead><tr><?php foreach($editorItemLabels as $label):?><th><?=e($label)?></th><?php endforeach?><th></th></tr></thead><tbody><?php foreach($editorRows as $r):$d=!empty($r['details_json'])?(json_decode($r['details_json'],true)?:[]):[];?><tr><td><input name="property_number[]" value="<?=e($r['property_number']??'')?>"></td><td><input name="unit[]" value="<?=e($d['Unit']??'')?>"></td><td><textarea name="description[]" required><?=e($r['description']??'')?></textarea></td><td><input type="number" step="any" name="quantity[]" value="<?=e($r['quantity']??'1')?>"></td><td><input name="item_status[]" value="<?=e($r['status']??'')?>"></td><td><button type="button" class="remove" onclick="this.closest('tr').remove()">Remove</button></td></tr><?php endforeach?></tbody></table></div></div>
    <div class="editor-grid signatures-input"><label>Requested / Prepared By<input name="requested_by" value="<?=e($editorDetails['Requested By']??$editorDetails['Prepared By']??'')?>"></label><label>Approved / Certified By<input name="approved_by" value="<?=e($editorDetails['Approved By']??$editorDetails['Certified Correct']??'')?>"></label><label>Issued / Inspected By<input name="issued_by" value="<?=e($editorDetails['Issued By']??$editorDetails['Inspection Committee Chairperson']??'')?>"></label><label>Received By<input name="received_by" value="<?=e($editorDetails['Received By']??$editorDetails['Supply and/or Property Custodian']??'')?>"></label></div>
    <div class="actions"><button class="btn primary">Save form</button><a class="btn" href="?page=forms&type=<?=urlencode($formType)?>">Cancel</a></div>
  </form>
</section>
<template id="itemRow"><tr><td><input name="property_number[]"></td><td><input name="unit[]"></td><td><textarea name="description[]" required></textarea></td><td><input type="number" step="any" name="quantity[]" value="1"></td><td><input name="item_status[]"></td><td><button type="button" class="remove" onclick="this.closest('tr').remove()">Remove</button></td></tr></template>
<script>function addItemRow(){document.querySelector('#itemTable tbody').append(document.getElementById('itemRow').content.cloneNode(true))}document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.paper')?.setAttribute('hidden','');const empty=[...document.querySelectorAll('.panel.empty')].find(x=>x.textContent.includes('printing'));if(empty)empty.hidden=true;});</script>
